### ISSUE TITLE
Object-Oriented Analysis

### ISSUE THREAD

**Issue by AivanD** [CMPUT301W24T03/Emoji301#28]
Document your initial object-oriented analysis using CRC cards, focusing on the most important anticipated classes, their responsibilities, and collaborators.

**Comment by AivanD** [comment]
![Image](https://github.com/CMPUT301W24T03/Emoji301/assets/97413218/8b7afa23-3aa1-49aa-bea6-6fae45358825)

**Comment by akila-edirisinghe** [comment]
![Image](https://github.com/CMPUT301W24T03/Emoji301/assets/93345272/55e53357-674b-493e-b79e-9d6f26175166)

**Comment by SnehalRay** [comment]
![CMPUT301 CRC (2)](https://github.com/CMPUT301W24T03/Emoji301/assets/113328542/000b7cf9-ddaa-4623-a3cb-d6bea311e149)

Subject to change
